### ISSUE TITLE
is there a way to detect this capabilities ?

### ISSUE THREAD

**Issue by jeromeetienne** [googlevr/chromium-webar#1]
Hi,

First and foremost, thanks for all the good work! it is amazing :) 

im writing a webar playground application which support chromium-webar. so i need to way to identify if the app is running on chromium-webar or on a normal chrome. Is there a way for me to detect this feature from javascript ?

Thanks

**Comment by jeromeetienne** [comment]
Currently im using something quite ugly and depending on the current build. im guessing it should be a better way :)

```
var isChromiumWebar = navigator.userAgent.match('Chrome/57.0.2987.5') !== null
```

**Comment by judax** [comment]
Yes, there is. As stated in the documentation, there are 2 levels to identify the capabilities:

1.- When you request the VRDisplays, check that the name is the right one. In this case, the name of the device that provides all these capabilities is "Tango VR Device".
2.- Another option is to check what capabilities the device/VRDisplay instance has. http://judax.github.io/webar/doc/webarapi/VRDisplayCapabilities.html. You can check if the device has a see through camera and/or a point cloud.

Hope this helps.

**Comment by jeromeetienne** [comment]
thanks!
