### ISSUE TITLE
window.localStorage === null ?

### ISSUE THREAD

**Issue by jeromeetienne** [googlevr/chromium-webar#14]
localStorage is not supported in chromium-webar ? im guessing this is just a flag missing somewhere. 

```
console.log(localStorage)
```

![screen shot 2017-07-13 at 11 28 10](https://user-images.githubusercontent.com/252962/28162265-5edd5b7c-67be-11e7-852d-8e7f53869fa9.png)

**Comment by judax** [comment]
This issue has been resolved in the current APK as stated in the issue #2 . Closing.
