### ISSUE TITLE
Render videoMesh on three.js r84 fails

### ISSUE THREAD

**Issue by jeromeetienne** [googlevr/chromium-webar#16]
- and aframe 0.6.0 is three.js r84 so rendering videoMesh on aframe is causing error.
- the same code works with three.js r86, but fail in three.js r84 and r85
- find below a screenshot of the error.

![screen shot 2017-07-29 at 15 59 33](https://user-images.githubusercontent.com/252962/28745770-2aea05a2-7477-11e7-8101-5db6f4fb7680.png)

**Comment by jeromeetienne** [comment]
my guess is that it is around the videoMesh build and how it handle the Uniforms. 

im stuck with no idea how to fix :( any hint ?

**Comment by jeromeetienne** [comment]
## Possible workaround
- recompile aframe.js with three.js r86
-  'You can do your own custom build with the master branch by bumping the three version on the package.json file'
- i did it, and it worked. it is possible to render the tango video mesh with aframe.js

**Comment by judax** [comment]
This issue has been resolved in threejs r86 as stated. Another possible option is to be able to modify ThreeJS as stated in the [documentation](https://github.com/googlevr/chromium-webar#using-the-webar-apis-in-threejs).
