### ISSUE TITLE
Surface reconstruction from point cloud

### ISSUE THREAD

**Issue by Utopiah** [googlevr/chromium-webar#18]
Useful to better interact with the environment beyond finding planes e.g. for physic systems or ray casting.

Could be done using marching cubes in threejs (or maybe GLSL if there is a significant performance gain). Current hardware won't allow for real time but... hopefully next iterations will. Still something that will be required overall for WebVR in the long run.

**Comment by judax** [comment]
There is a mesh reconstruction API in Tango. I am working on adding it. Cannot provide a good estimate on the ETA as we are focused on the ARCore launch now and the adaptation of this repo to match some ARCore/Tango commonalities.
