### ISSUE TITLE
Add support for ARCore and then get this into mainline Chrome

### ISSUE THREAD

**Issue by bhouston** [googlevr/chromium-webar#19]
So can we upgrade this project to include support for ARCore as the default implementation:

https://www.blog.google/products/google-vr/arcore-augmented-reality-android-scale/

And then schedule this for release in mainline Chrome?  This is greatly needed.

**Comment by bhouston** [comment]
Oh, there is this separate project: https://github.com/google-ar/WebARonARCore

**Comment by judax** [comment]
Yes. We will cleanup this project a bit a make it compatible (up to what is possible) with WebARonARCore.
