### ISSUE TITLE
localstorage isnt available 

### ISSUE THREAD

**Issue by jeromeetienne** [googlevr/chromium-webar#2]
```window.localStorage``` is null. It is impossible to store things in there.

Could we make it available ?

![screen shot 2017-05-29 at 14 44 50](https://cloud.githubusercontent.com/assets/252962/26552078/7d5687d6-447d-11e7-821a-22200fe7fe22.png)

**Comment by judax** [comment]
Yes, forgot to enable it in Chromium. Pushed a new version that should resolve this issue.

**Comment by jeromeetienne** [comment]
excelent! thanks!
