### ISSUE TITLE
unable to trigger fullscreen

### ISSUE THREAD

**Issue by jeromeetienne** [googlevr/chromium-webar#3]
Hi

im trying to get the browser fullscreen to remove the 'ugly location bar', Thus i could get nicer looking UX and videos. 

But the usual javascript api seems to silently fails. The following code works without issue on chrome desktop/mobile.. but not in chrome-webar.

Is there anyway to trigger fullscreen ?

Thanks

```
	document.querySelector('#buttonFullscreen').addEventListener('click', function(){
		var domElement = document.body
		if (domElement.requestFullscreen) {
			domElement.requestFullscreen();
		} else if (domElement.mozRequestFullScreen) {
			domElement.mozRequestFullScreen();
		} else if (domElement.webkitRequestFullscreen) {
			domElement.webkitRequestFullscreen();
		} else if (domElement.msRequestFullscreen) {
			domElement.msRequestFullscreen();
		}		
	})
```

**Comment by judax** [comment]
As the prototype is using the WebView flavor of Chromium the UI (navigation bar) is custom and thus, the fullscreen functionality is not enabled for now. Sorry. We might work on supporting full chromium soon and a lot of problems (this included) will be solved.

**Comment by jeromeetienne** [comment]
cool, keep on the good work!
