### ISSUE TITLE
Any update of ChromiumAR?

### ISSUE THREAD

**Issue by godlzr** [googlevr/chromium-webar#8]
The current version is really unstable and low FPS, my test threejs scene is only around 5~15 fps and always crashes no problem on chrome(seems like memory leak issue).
Really need a stable and usable ChromiumAR.
Working on tango development tablet.

**Comment by jeromeetienne** [comment]
i run on lenovo phab2 pro, and i experience frequent application crashes too. (when picking or changing phone orientation)

**Comment by judax** [comment]
Some of these problems are related to using the WebView flavor of Chromium. We have been working on some improvements but still there are some things that cannot overcome. Hopefully we will get some help from seasoned Chromium developers soon to be able to implement AR in a full featured Chromium build so stay tuned. In the meantime, I would recommend to kill the app frequently (I know, not ideal). We have been able to build some complex prototypes we will be announcing soon but admit that this is still highly experimental.

Also, please, provide full logcat output of a crash to try to see if there is something that can be improved.
