### ISSUE TITLE
Any chance Area Learning is going to be exposed?

### ISSUE THREAD

**Issue by blairmacintyre** [googlevr/chromium-webar#9]
It would be great to have access to more of the underlying Tango APIs.  Or perhaps it is and I missed that?

**Comment by judax** [comment]
Added support for basic ADF handling. Please, review the API documentation and the new ADF basic example.

**Comment by Utopiah** [comment]
What about creating ADFs without relying on a tool/app?

**Comment by judax** [comment]
That is an interesting feature. Actually, Tango even enables real time ADF construction while motion tracking is happening to try to recover in extreme cases (not enough tracking points in the image for quite some time, strong shakes that make the IMUs go "crazy", ...). Even this feature has not been exposed. We still have to figure out what the JS API would look like in those cases (enabling real time ADFs/localization, saving an ADF from the web app itself, ...).

**Comment by blairmacintyre** [comment]
The first question, really, is "what features might be generic, what are Tango specific"?  Any webar API is going to have platform specific APIs in it:  all the platforms have unique and interesting features that we want to enable.  

Unless Google and Microsoft are going to agree on a common format and interoperability for ADFs and Hololens maps (<insert maniacal laughter>) it's probably best to just agree up front that some parts are going to be platform specific.  Just create a "webar.tango." (and "webar.arkit." since I see you already have some arkit code in you .js files) and put those APIs there.

There are things that can be transparently shared, and reasonable defaults that can be chosen for different platforms, but trying to hide the platform behind a single API will result in webar being hamstrung from the start.  VR is shockingly simple compared to AR, and even WebVR is having issues trying to "unify".

**Comment by Utopiah** [comment]
What about being able to load an ADF (or maps or whatever abstraction is agreed upon) via URL? That could be an alternative to being able to create and save via a WebAR page.
